# Generated by Django 2.1.4 on 2018-12-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='p_users',
            field=models.ManyToManyField(to='Admin.AdminUser'),
        ),
    ]
