# Generated by Django 2.1.4 on 2018-12-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=64)),
                ('m_duration', models.IntegerField(default=90)),
                ('m_leading_role', models.CharField(max_length=128)),
                ('m_director', models.CharField(max_length=64)),
                ('m_open_day', models.DateTimeField(default='1970-1-1 00:00:00')),
                ('m_mode', models.CharField(max_length=32)),
            ],
        ),
    ]
